# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: "3.10"
        cache: pip
        
    - name: Configure CMake
      run: |
        python -m venv env;
        .\env\Scripts\Activate.ps1;
        python -m pip install jinja2;
        python --version;
        cmake -Bbuild --clean-first -DCMAKE_BUILD_TYPE=Release -S ${{ github.workspace }}

    - name: Build
      run: | 
        .\env\Scripts\Activate.ps1;
        python --version;
        cmake --build build --config Release --clean-first

    - name: Test
      working-directory: build
      run: ctest --build-config Release
